version: '3'

services:
  nextcloud:
    image: nextcloud:fpm-alpine
    hostname: nextcloud-app
    container_name: nextcloud-app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - nextcloudapps:/var/www/html/custom_apps
      - nextcloudconfig:/var/www/html/config
      - nextclouddata:/var/www/html/data
      - DOMAIN=${DOMAINNAME}
      - ./mail-cloud/conf/php_max_upload_limit.ini:/usr/local/etc/php/conf.d/zzz-php_max_upload_limit.ini
    environment:
      - SQLITE_DATABASE=nextcloud
    networks:
      - default

  web:
    build: ./mail-cloud/web
    restart: always
    hostname: nextcloud-web
    container_name: nextcloud-web
    volumes:
      - nextcloud:/var/www/html:ro
      - nextcloudapps:/var/www/html/custom_apps:ro
      - nextcloudconfig:/var/www/html/config:ro
      - nextclouddata:/var/www/html/data:ro
    environment:
      - VIRTUAL_HOST=cloud.${DOMAINNAME}
      - LETSENCRYPT_HOST=cloud.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=support@${DOMAINNAME}
    depends_on:
      - nextcloud
    networks:
      - proxy-tier
      - default

  collabora:
    image: collabora/code
    container_name: nextcloud-collabora
    hostname: nextcloud-collabora
    restart: unless-stopped
    networks:
      - default
    environment:
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - VIRTUAL_HOST=office.cloud.${DOMAINNAME}
      - LETSENCRYPT_HOST=office.cloud.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=support@${DOMAINNAME}
      - domain=cloud.${DOMAINNAME}
      - dictionaries=en
    cap_add:
      - MKNOD
    tty: true
    networks:
      - proxy-tier
      - default

  nextcloud-manager:
    build: ./mail-cloud/manager
    hostname: nextcloud-manager
    container_name: nextcloud-manager
    volumes:
      - nextcloud:/var/www/html
      - nextcloudapps:/var/www/html/custom_apps
      - nextcloudconfig:/var/www/html/config
      - nextclouddata:/var/www/html/data
    depends_on: 
      - nextcloud

volumes:
  nextcloud:
    driver: local
  nextcloudapps:
    driver: local
  nextcloudconfig:
    driver: local
  nextclouddata:
    driver: local

networks:
  proxy-tier: