version: '3'
services:
  mail:
    build: ./mail-server/.
    hostname: ${MAIL_HOSTNAME}.${DOMAINNAME}
    domainname: ${DOMAINNAME}
    container_name: ${MAIL_CONTAINER_NAME}
    ports:
    - 25:25
    - 143:143
    - 587:587
    - 993:993
    - 4190:4190
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./mail-server/config/:/tmp/docker-mailserver/
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    depends_on:
      - mailmanager

  mailmanager:
    build: ./mail-server/manager
    hostname: mail-manager
    container_name: mail-manager
    volumes:
      - maildata:/var/mail
      - ./mail-server/config/:/tmp/docker-mailserver/
    environment:
      - VIRTUAL_HOST=api.mail.${DOMAINNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=mailman.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=support@${DOMAINNAME}
    env_file:
      - .env
      - env-mailserver
    restart: always
    networks:
      - proxy-tier
      - default

  autodiscovery:
    image: jsmitsnl/docker-email-autodiscover:latest
    hostname: autodiscover
    domainname: autodiscover.${MAIL_HOSTNAME}.${DOMAINNAME}
    container_name: mail-autodiscover
    restart: always
    environment:
    - DOMAIN=autodiscover.${MAIL_HOSTNAME}.${DOMAINNAME}
    - IMAP_HOST=${MAIL_HOSTNAME}.${DOMAINNAME}
    - SMTP_HOST=${MAIL_HOSTNAME}.${DOMAINNAME}
    - VIRTUAL_HOST=autoconfig.${MAIL_HOSTNAME}.${DOMAINNAME},autodiscover.${MAIL_HOSTNAME}.${DOMAINNAME}
    - LETSENCRYPT_HOST=autoconfig.${MAIL_HOSTNAME}.${DOMAINNAME},autodiscover.${MAIL_HOSTNAME}.${DOMAINNAME}
    - LETSENCRYPT_EMAIL=support@${DOMAINNAME}
    networks:
    - proxy-tier
    - default
    
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local

networks:
  proxy-tier:
